# 配置服务器的端口，通常设置为8888:
server:
  port: ${APP_PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    # 从本地文件读取配置时，Config Server激活的profile必须设定为native:
    active: native
  cloud:
    config:
      server:
        # 禁用 JdbcEnvironmentRepository 的自动配置。
        jdbc:
          enabled: false
        native:
          # 设置配置文件的搜索路径:
          search-locations: classpath:./config-repo, classpath:../config-repo, classpath:../../config-repo

#  parent模块不要直接引入带有jdbc的依赖，最好放在dependencyManagement中，各模块按需引入
#  如果依赖库中有spring-boot-starter-jdbc，必须配置DataSource
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fmock
#    username: root
#    password: root



