# application.yml是所有应用的全局默认配置
spring:
  cache:
    redis:
      time-to-live: 600s  # 默认缓存过期时间，可覆盖
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fmock?serverTimezone=UTC
    username: root
    password: ${DB_PW:root}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      #password:
      database: ${REDIS_DATABASE:0}
      database1: ${REDIS_DATABASE1:1}
#      ssl:
#      timeout:
#      connectTimeout:
#      clientName:
#      cluster:
#        nodes:
#      sentinel:
#        master:
#        nodes:

storage:
  local:
    # 文件存储根目录:
    root-dir: ${STORAGE_LOCAL_ROOT:/var/storage}
    max-size: ${STORAGE_LOCAL_MAX_SIZE:102400}
    allow-empty: false
    allow-types: jpg, png, gif

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
